#theme: readthedocs
site_name: obestwalter

pages:
  - Home: index.md

repo_url: https://github.com/obestwalter

strict: False

markdown_extensions:
  - toc:
      permalink: Â¶

remote_branch: master
remote_name: source
